name: Deploy Application

on:
  workflow_call:

    inputs:
      environment:
        required: true
        type: string

jobs:

  deploy:

    name: Deploy to ${{ inputs.environment }}

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          echo "Deploying application"
          echo "Environment: ${{ inputs.environment }}"

      - name: Show application environment
        run: |
          echo "APP_ENV=${{ vars.APP_ENV }}"

      - name: Deploy
        run: |
          echo "Deploying Python application..."